### ISSUE TITLE
Division by zero in Probability\Distribution\Continuous\Continuous

### ISSUE THREAD

**Issue by drjayvee** [markrogoyski/math-php#429]
[Contiuous.php:39](https://github.com/markrogoyski/math-php/blob/4dab1f0efe96b547bd21b17b66a5b7efec5902b3/src/Probability/Distribution/Continuous/Continuous.php#L39) can trigger a division by zero Warning.

Specifically, this happens in our project with the following call `(new MathPHP\Statistics\Regression\Linear($points))->ci($x, 0.05);`.

Call stack:
```
#8 /vendor/markrogoyski/math-php/src/Probability/Distribution/Continuous/Continuous.php(39): MathPHP\Probability\Distribution\Continuous\Continuous::inverse
#7 /vendor/markrogoyski/math-php/src/Probability/Distribution/Continuous/StudentT.php(130): MathPHP\Probability\Distribution\Continuous\StudentT::inverse2Tails
#6 /vendor/markrogoyski/math-php/src/Statistics/Regression/Methods/LeastSquares.php(730): MathPHP\Statistics\Regression\Linear::ci
...
```

I'm sorry I can't contribute a patch for this. There's a reason we're using a math library ;p

**Comment by markrogoyski** [comment]
This unit test will reproduce the issue.

```php
    public function testBugIssue429()
    {
        // Given
        $points = [[5,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,0],[8,1],[8,0],[8,1],[8,1],[8,1],[8,1],[8,0],[8,1],[8,0],[8,1],[8,0],[8,1],[8,0],[8,1],[8,0],[8,1],[8,1],[8,1],[8,0],[8,1],[8,0],[8,1],[8,1],[8,1],[8,0],[8,1],[8,0],[8,1],[8,0],[8,1],[8,0],[8,1],[8,0],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1],[8,1]];
        $x      = 5.0;

        // And
        $regression = new Linear($points);

        // When
        $ci = $regression->ci($x, 0.05);
    }
```

It produces this stack trace:
```
There was 1 error:

1) MathPHP\Tests\Statistics\Regression\LinearTest::testBugIssue429
DivisionByZeroError: Division by zero

math-php/src/Probability/Distribution/Continuous/Continuous.php:39
math-php/src/Probability/Distribution/Continuous/StudentT.php:130
math-php/src/Statistics/Regression/Methods/LeastSquares.php:730
math-php/tests/Statistics/Regression/LinearTest.php:558
```

The division by zero happens when computing the guess in the Continues `inverse` function:
```php
        while ($dif > $tolerance) {
            $y = $this->cdf($guess);

            // Since the CDF is the integral of the PDF, the PDF is the derivative of the CDF
            $slope = $this->pdf($guess);
            $del_y = $target - $y;
            $guess = $del_y / $slope + $guess; // <---- this is where the division by zero happens
```

With the test inputs, these are the values at the time of the crash:
- del_y: 0.475
- slope: 0
- guess: 0

**Comment by markrogoyski** [comment]
The issue looks like it is in the StudentT distribution's PDF.

This unit test using the data from this bug currently fails, producing 0 instead of the expected result.

```php
    public function testBugIssue429StudentTPdf()
    {
        // Given
        $v = 341;
        $studentT = new StudentT($v);

        // When
        $t = 0;
        $pdf = $studentT->pdf($t);

        // Then
        $expected = 0.3986499;
        $this->assertEqualsWithDelta($expected, $pdf, 0.001);
    }
```

```
There was 1 failure:

1) MathPHP\Tests\Statistics\Regression\LinearTest::testBugIssue429StudentTPdf
Failed asserting that 0.0 matches expected 0.3986499.
```

R code that generated the test data result:
```R
> library(stats)
> v <- 341
> t <- 0
> dt(t, v)
[1] 0.3986499
```

This online calculator also confirms the result: https://keisan.casio.com/exec/system/1180573203
Producing: 0.398649908330383416563

The StudentT's PDF is calculated using the gamma special function. The denominator is calculating gamma(341/2) which is producing infinity, which is where the 0 value seems to be coming from.

For the same value, R produces an extremely large number, which for all intents and purposes, is the same as infinity.
```R
> gamma(341/2)
[1] 5.562092e+305
```

Is there an alternate way to calculate the StudentT PDF? I'm not familiar with this or gamma, but numbers this high are basically at the limit of what PHP can handle on a 64-bit machine:
```php
php > echo \PHP_INT_MAX;
9223372036854775807
php > echo \PHP_FLOAT_MAX;
1.7976931348623E+308
```

@Beakerboy when you have time can you investigate this further? Seems like StudentT PDF is supposed to be able to produce a result here, and maybe being smarter with calculating and applying the gamma function arithmetic, or calculating it some other way, might lead to a better result? Regardless, the StudentT PDF unit tests don't have any test data with values over 10, so maybe that would be a good place to start: add some higher values and see where it breaks down. I'll add some additional unit tests and see how high it can go and still get reasonable results matching R.

**Comment by markrogoyski** [comment]
I added additional test cases for the StudentT `pdf` up until the point where the tests still pass. The library works fine up until a `v` of 301. For values 302 up to 334 the `pdf` returns 0. For values above that it produces either 0, INF, or NAN. I put some commented out test cases that fail with the expected results.

**Comment by Beakerboy** [comment]
In theory, at this height of degrees of freedom the standard normal could probably be used instead of T with minimal loss of precision.

**Comment by Beakerboy** [comment]
R Source for dt function:
https://github.com/wch/r-source/blob/79298c499218846d14500255efd622b5021c10ec/src/nmath/dt.c

**Comment by Beakerboy** [comment]
A pull request has been submitted which should fix this issue. It needs to be cleaned up to clarify what it is doing, but it should work for you while we make it pretty.

**Comment by Beakerboy** [comment]
I have r code above that should give the correct result. I’ll probably just port the cdf and inverse functions from the C sources that R uses as well. I think I have some idea of what the functions are doing after reading the source paper. I found a couple typos though which makes it harder.

**Comment by Beakerboy** [comment]
will need to:

- Refactor StudentT::cdf()
- Refactor Beta::cdf()
- Add Special::logBeta()
- Add SpeciallogGamma()
- PROFIT!

**Comment by markrogoyski** [comment]
@drjayvee,

This has been fixed in [Version 2.5.0](https://github.com/markrogoyski/math-php/releases/tag/v2.5.0). You should not get any more division by zero errors.

Many thanks to @Beakerboy for numerous improvements in the special functions that drive these distributions.

**Comment by drjayvee** [comment]
Thanks a bunch! I'm upgrading as we speak.
